on:
  pull_request:
    branches: ["*"]
    tags-ignore:
      - "release-please--*" # Exclude tags containing "staging"

name: test build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - uses: actions/setup-go@v5
        if: ${{ steps.release.outputs.release_created }}
        with:
          go-version: "^1.23.3"

      - name: Build project and prepare release artifact
        if: ${{ steps.release.outputs.release_created }}
        run: |
          env GOOS=darwin GOARCH=amd64 go build -ldflags "-X cpenv/cmd.Version=${{ steps.release.outputs.tag_name }}" -o ./compile/cpenv-darwin-arm64 ./main.go
          env GOOS=darwin GOARCH=amd64 go build -ldflags "-X cpenv/cmd.Version=${{ steps.release.outputs.tag_name }}" -o ./compile/cpenv-darwin-amd64 ./main.go
          env GOOS=darwin GOARCH=386 go build -ldflags "-X cpenv/cmd.Version=${{ steps.release.outputs.tag_name }}" -o ./compile/cpenv-darwin-386 ./main.go
